site_name: DW
theme:
  disable_nav_previous_next: true
  name: null
  custom_dir: 'cinder'
  locale: pt_BR
  highlightjs: true
  colors:
    primary: '#FF5733'
    secondary: '#C70039'
  hljs_languages:
    - yaml
    - python
    - html
    - css
    - javascript
plugins:
   - search
repo_url: "https://github.com/jonh-carvalho/DW_25.1_8001"
extra:
  collapse_toc: true
  toc_depth: 0


